### ISSUE TITLE
Crashes at launch for me

### ISSUE THREAD

**Issue by Voljega** [lbrpdx/retrotrivia#5]
I am on Batocera v32, and I'm not having any videos for the games if maybe that's the issue.
I do have some EasyRPG games
(killed it with emukill at the end)

```
killall: evmapy: no process killed
2021-12-29 07:09:56,674 ERROR (emulatorlauncher.py:303):runCommand /usr/bin/batocera-pygame: line 5: unclutter-remote: command not found
[2021-12-29 07:07:00,919] Game screen: 1920x1080
[2021-12-29 07:07:00,920] Number of joysticks found: 1
[2021-12-29 07:07:00,920] Joystick 0 initialized as 030000005e040000a102000000010000 / 0
[2021-12-29 07:07:01,403] Loaded system 3do with 0 games.
[2021-12-29 07:07:01,404] Loaded system 3ds with 0 games.
[2021-12-29 07:07:01,478] Loaded system amiga1200 with 0 games.
[2021-12-29 07:07:01,495] Loaded system amiga500 with 0 games.
[2021-12-29 07:07:01,498] Loaded system amigacd32 with 0 games.
[2021-12-29 07:07:01,498] Loaded system amigacdtv with 0 games.
[2021-12-29 07:07:01,651] Loaded system amstradcpc with 0 games.
[2021-12-29 07:07:01,651] Loaded system apple2 with 0 games.
[2021-12-29 07:07:01,680] Loaded system atari2600 with 0 games.
[2021-12-29 07:07:01,686] Loaded system atari5200 with 0 games.
[2021-12-29 07:07:01,690] Loaded system atari7800 with 0 games.
[2021-12-29 07:07:01,691] Loaded system atari800 with 0 games.
[2021-12-29 07:07:01,736] Loaded system atarist with 0 games.
[2021-12-29 07:07:01,753] Loaded system atomiswave with 0 games.
[2021-12-29 07:07:01,764] Loaded system c128 with 0 games.
[2021-12-29 07:07:01,776] Loaded system c20 with 0 games.
[2021-12-29 07:07:01,795] Loaded system c64 with 0 games.
[2021-12-29 07:07:01,798] Loaded system channelf with 0 games.
[2021-12-29 07:07:01,808] Loaded system colecovision with 0 games.
[2021-12-29 07:07:01,810] Loaded system daphne with 0 games.
[2021-12-29 07:07:01,811] Loaded system dos with 0 games.
[2021-12-29 07:07:01,850] Loaded system dreamcast with 0 games.
[2021-12-29 07:07:01,851] Loaded system easyrpg with 0 games.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/userdata/roms/pygame/retrotrivia/retrotrivia.pygame", line 266, in load_all
    loaded_sys = gl.load(sys)
  File "/userdata/roms/pygame/retrotrivia/gamelists.py", line 33, in load
    short=item.text.split('(')[0] # Remove (USA, Europe...)
AttributeError: 'NoneType' object has no attribute 'split'
/usr/bin/batocera-pygame: line 9:  3062 Killed                  pygame "${ROM}"
/usr/bin/batocera-pygame: line 12: unclutter-remote: command not found
```

**Comment by lbrpdx** [comment]
You have 0 video scraped on your system by choice, right?
So, you want to play RetroTrivia with only the trivia questions, and no question about any of your games library at all?

**Comment by Voljega** [comment]
Yes and yes.

Well to be fair I mostly want to look at retrotrivia to see how pygame is looking and see if it's a good fit for a basic game engine idea I'm toying with ;)

**Comment by lbrpdx** [comment]
I couldn't repro, even with no video, but I put a tentative fix in https://github.com/lbrpdx/retrotrivia/blob/master/gamelists.py 
Can you please update this file and tell me if it fixes your issue?

**Comment by Voljega** [comment]
Just tested it, it fixes the issue
